In [1]:
import numpy as np

In [16]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [9]:
np.random.rand(3,4)#生成0~1均勻分布的數值3列4行

array([[0.85650244, 0.191299  , 0.36170383, 0.84874544],
       [0.80581113, 0.66625427, 0.44896861, 0.71544525],
       [0.71908935, 0.35915045, 0.01453644, 0.00307221]])

In [10]:
np.random.randn(3,3)#生成常態分布

array([[-0.1304283 , -1.61940997, -0.44023554],
       [ 1.63807651,  1.08725244, -0.78789507],
       [ 0.49456465,  0.5467486 , -0.87853612]])

In [17]:
np.random.randint(3,6,18)#隨機生成[3,6)間18個數

array([4, 5, 4, 3, 4, 3, 5, 5, 5, 3, 4, 4, 4, 5, 5, 5, 3, 4])